name: barpass_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  flex_color_scheme: ^8.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^3.0.0
  flutter_svg: ^2.2.1
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^16.2.1
  google_fonts: ^6.3.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.1
  mobile_scanner: ^7.1.2
  package_info_plus: ^9.0.0
  rive: ^0.13.20
  riverpod_annotation: ^3.0.0
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.0+1
  smooth_page_indicator: ^1.2.1
  smooth_sheets: ^0.15.0

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: 
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  riverpod_generator:
  riverpod_lint:
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/json/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300

flutter_launcher_icons:
  image_path: "assets/generation-icons/icon-light.png"

  android: "launcher_icon"
  adaptive_icon_foreground: "assets/generation-icons/icon-light-adaptive-fg.png"
  adaptive_icon_background: "assets/generation-icons/icon-light-adaptive-bg.png"
  adaptive_icon_monochrome: "assets/generation-icons/icon-monochrome.png"
  adaptive_icon_foreground_inset: 0

  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  image: assets/splash/splash-icon-fg.png
  color: "#ffffff"
  android_12:
    image: assets/splash/splash-icon-fg-12.png
    color: "#ffffff"
    icon_background_color: "#ffffff"

